const std = @import("std");

const sorvi = @import("sorvi");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const sdl2_compat = b.option(bool, "sdl2_compat", "rename symbols for sdl2-compat") orelse false;

    const sorvi_dep = b.dependency("sorvi", .{
        .target = target,
        .optimize = optimize,
    });

    const sorvi_api = sorvi.createSorviAPI(b, .{
        .target = target,
        .api = .core,
        .extensions = &.{
            "ext",
            "core_v1",
            "mem_v1",
            "thread_v1",
            "fs_v1",
            "kbm_v1",
            "audio_v1",
            "video_v1",
            "raster_v1",
            "vulkan_v1",
            "gles_v1",
        },
    });

    const sdl3_dep = b.dependency("SDL3", .{
        .target = sorvi.resolveSorviTarget(b, target.query),
        .optimize = optimize,
    });

    const sysroot = sorvi.createSysroot(b, .{
        .target = sorvi.resolveSorviTarget(b, target.query),
        .optimize = optimize,
        .include_libc = true,
    });

    const build_config_h: *std.Build.Step.ConfigHeader = build_config_h: {
        const cpu = target.result.cpu;
        const x86 = cpu.arch.isX86();
        const arm = cpu.arch.isArm();
        const aarch64 = cpu.arch.isAARCH64();
        const loongarch = cpu.arch == .loongarch32 or cpu.arch == .loongarch64;
        break :build_config_h b.addConfigHeader(.{
            .style = .{ .cmake = sdl3_dep.path("include/build_config/SDL_build_config.h.cmake") },
            .include_path = "SDL_build_config.h",
        }, .{
            .SDL_PLATFORM_PRIVATE = true,
            .HAVE_GCC_ATOMICS = false,
            .HAVE_GCC_SYNC_LOCK_TEST_AND_SET = false,
            .SDL_DISABLE_ALLOCA = false,
            .HAVE_FLOAT_H = true,
            .HAVE_STDARG_H = true,
            .HAVE_STDDEF_H = true,
            .HAVE_STDINT_H = true,
            .HAVE_LIBC = true,
            .HAVE_ALLOCA_H = true,
            .HAVE_ICONV_H = true,
            .HAVE_INTTYPES_H = true,
            .HAVE_LIMITS_H = true,
            .HAVE_MALLOC_H = true,
            .HAVE_MATH_H = true,
            .HAVE_MEMORY_H = true,
            .HAVE_SIGNAL_H = true,
            .HAVE_STDIO_H = true,
            .HAVE_STDLIB_H = true,
            .HAVE_STRINGS_H = true,
            .HAVE_STRING_H = true,
            .HAVE_SYS_TYPES_H = true,
            .HAVE_WCHAR_H = true,
            .HAVE_PTHREAD_NP_H = false,
            .HAVE_DLOPEN = false,
            .HAVE_MALLOC = true,
            .HAVE_FDATASYNC = false,
            .HAVE_GETENV = true,
            .HAVE_GETHOSTNAME = false,
            .HAVE_SETENV = false,
            .HAVE_PUTENV = false,
            .HAVE_UNSETENV = false,
            .HAVE_ABS = true,
            .HAVE_BCOPY = true,
            .HAVE_MEMSET = true,
            .HAVE_MEMCPY = true,
            .HAVE_MEMMOVE = true,
            .HAVE_MEMCMP = true,
            .HAVE_WCSLEN = true,
            .HAVE_WCSNLEN = true,
            .HAVE_WCSLCPY = true,
            .HAVE_WCSLCAT = true,
            .HAVE_WCSSTR = true,
            .HAVE_WCSCMP = true,
            .HAVE_WCSNCMP = true,
            .HAVE_WCSTOL = true,
            .HAVE_STRLEN = true,
            .HAVE_STRNLEN = true,
            .HAVE_STRLCPY = true,
            .HAVE_STRLCAT = true,
            .HAVE_STRPBRK = true,
            .HAVE__STRREV = false,
            .HAVE_INDEX = false,
            .HAVE_RINDEX = false,
            .HAVE_STRCHR = true,
            .HAVE_STRRCHR = true,
            .HAVE_STRSTR = true,
            .HAVE_STRNSTR = false,
            .HAVE_STRTOK_R = true,
            .HAVE_ITOA = false,
            .HAVE__LTOA = false,
            .HAVE__UITOA = false,
            .HAVE__ULTOA = false,
            .HAVE_STRTOL = true,
            .HAVE_STRTOUL = true,
            .HAVE__I64TOA = false,
            .HAVE__UI64TOA = false,
            .HAVE_STRTOLL = true,
            .HAVE_STRTOULL = true,
            .HAVE_STRTOD = true,
            .HAVE_ATOI = true,
            .HAVE_ATOF = true,
            .HAVE_STRCMP = true,
            .HAVE_STRNCMP = true,
            .HAVE_VSSCANF = true,
            .HAVE_VSNPRINTF = true,
            .HAVE_ACOS = true,
            .HAVE_ACOSF = true,
            .HAVE_ASIN = true,
            .HAVE_ASINF = true,
            .HAVE_ATAN = true,
            .HAVE_ATANF = true,
            .HAVE_ATAN2 = true,
            .HAVE_ATAN2F = true,
            .HAVE_CEIL = true,
            .HAVE_CEILF = true,
            .HAVE_COPYSIGN = true,
            .HAVE_COPYSIGNF = true,
            .HAVE__COPYSIGN = false,
            .HAVE_COS = true,
            .HAVE_COSF = true,
            .HAVE_EXP = true,
            .HAVE_EXPF = true,
            .HAVE_FABS = true,
            .HAVE_FABSF = true,
            .HAVE_FLOOR = true,
            .HAVE_FLOORF = true,
            .HAVE_FMOD = true,
            .HAVE_FMODF = true,
            .HAVE_ISINF = true,
            .HAVE_ISINFF = false,
            .HAVE_ISINF_FLOAT_MACRO = true,
            .HAVE_ISNAN = true,
            .HAVE_ISNANF = false,
            .HAVE_ISNAN_FLOAT_MACRO = true,
            .HAVE_LOG = true,
            .HAVE_LOGF = true,
            .HAVE_LOG10 = true,
            .HAVE_LOG10F = true,
            .HAVE_LROUND = true,
            .HAVE_LROUNDF = true,
            .HAVE_MODF = true,
            .HAVE_MODFF = true,
            .HAVE_POW = true,
            .HAVE_POWF = true,
            .HAVE_ROUND = true,
            .HAVE_ROUNDF = true,
            .HAVE_SCALBN = true,
            .HAVE_SCALBNF = true,
            .HAVE_SIN = true,
            .HAVE_SINF = true,
            .HAVE_SQRT = true,
            .HAVE_SQRTF = true,
            .HAVE_TAN = true,
            .HAVE_TANF = true,
            .HAVE_TRUNC = true,
            .HAVE_TRUNCF = true,
            .HAVE__FSEEKI64 = false,
            .HAVE_FOPEN64 = false,
            .HAVE_FSEEKO = true,
            .HAVE_FSEEKO64 = false,
            .HAVE_MEMFD_CREATE = false,
            .HAVE_POSIX_FALLOCATE = false,
            .HAVE_SIGACTION = false,
            .HAVE_SIGTIMEDWAIT = false,
            .HAVE_SA_SIGACTION = false,
            .HAVE_ST_MTIM = false,
            .HAVE_SETJMP = false,
            .HAVE_NANOSLEEP = true,
            .HAVE_GMTIME_R = false,
            .HAVE_LOCALTIME_R = false,
            .HAVE_NL_LANGINFO = false,
            .HAVE_SYSCONF = false,
            .HAVE_SYSCTLBYNAME = false,
            .HAVE_CLOCK_GETTIME = true,
            .HAVE_GETPAGESIZE = true,
            .HAVE_ICONV = true,
            .SDL_USE_LIBICONV = false,
            .HAVE_PTHREAD_SETNAME_NP = false,
            .HAVE_PTHREAD_SET_NAME_NP = false,
            .HAVE_SEM_TIMEDWAIT = true,
            .HAVE_GETAUXVAL = false,
            .HAVE_ELF_AUX_INFO = false,
            .HAVE_PPOLL = false,
            .HAVE__EXIT = true,
            .HAVE_GETRESUID = false,
            .HAVE_GETRESGID = false,
            .HAVE_DBUS_DBUS_H = false,
            .HAVE_FCITX = false,
            .HAVE_IBUS_IBUS_H = false,
            .HAVE_INOTIFY_INIT1 = false,
            .HAVE_INOTIFY = false,
            .HAVE_LIBUSB = false,
            .HAVE_O_CLOEXEC = true,
            .HAVE_LINUX_INPUT_H = false,
            .HAVE_LIBUDEV_H = false,
            .HAVE_LIBDECOR_H = false,
            .HAVE_LIBURING_H = false,
            .HAVE_FRIBIDI_H = false,
            .SDL_FRIBIDI_DYNAMIC = "",
            .HAVE_LIBTHAI_H = false,
            .SDL_LIBTHAI_DYNAMIC = "",
            .HAVE_DDRAW_H = false,
            .HAVE_DSOUND_H = false,
            .HAVE_DINPUT_H = false,
            .HAVE_XINPUT_H = false,
            .HAVE_WINDOWS_GAMING_INPUT_H = false,
            .HAVE_GAMEINPUT_H = false,
            .HAVE_DXGI_H = false,
            .HAVE_DXGI1_5_H = false,
            .HAVE_DXGI1_6_H = false,
            .HAVE_MMDEVICEAPI_H = false,
            .HAVE_TPCSHRD_H = false,
            .HAVE_ROAPI_H = false,
            .HAVE_SHELLSCALINGAPI_H = false,
            .USE_POSIX_SPAWN = false,
            .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR = false,
            .HAVE_POSIX_SPAWN_FILE_ACTIONS_ADDCHDIR_NP = false,
            .SDL_DISABLE_DLOPEN_NOTES = true,
            .SDL_DEFAULT_ASSERT_LEVEL_CONFIGURED = false,
            .SDL_DEFAULT_ASSERT_LEVEL = null,
            .SDL_AUDIO_DISABLED = false,
            .SDL_VIDEO_DISABLED = false,
            .SDL_GPU_DISABLED = false,
            .SDL_RENDER_DISABLED = false,
            .SDL_CAMERA_DISABLED = false,
            .SDL_JOYSTICK_DISABLED = false,
            .SDL_HAPTIC_DISABLED = false,
            .SDL_HIDAPI_DISABLED = false,
            .SDL_POWER_DISABLED = false,
            .SDL_SENSOR_DISABLED = false,
            .SDL_DIALOG_DISABLED = false,
            .SDL_THREADS_DISABLED = false,
            .SDL_AUDIO_DRIVER_ALSA = false,
            .SDL_AUDIO_DRIVER_ALSA_DYNAMIC = "",
            .SDL_AUDIO_DRIVER_OPENSLES = false,
            .SDL_AUDIO_DRIVER_AAUDIO = false,
            .SDL_AUDIO_DRIVER_COREAUDIO = false,
            .SDL_AUDIO_DRIVER_DISK = false,
            .SDL_AUDIO_DRIVER_DSOUND = false,
            .SDL_AUDIO_DRIVER_DUMMY = true,
            .SDL_AUDIO_DRIVER_EMSCRIPTEN = false,
            .SDL_AUDIO_DRIVER_HAIKU = false,
            .SDL_AUDIO_DRIVER_JACK = false,
            .SDL_AUDIO_DRIVER_JACK_DYNAMIC = "",
            .SDL_AUDIO_DRIVER_NETBSD = false,
            .SDL_AUDIO_DRIVER_OSS = false,
            .SDL_AUDIO_DRIVER_PIPEWIRE = false,
            .SDL_AUDIO_DRIVER_PIPEWIRE_DYNAMIC = "",
            .SDL_AUDIO_DRIVER_PULSEAUDIO = false,
            .SDL_AUDIO_DRIVER_PULSEAUDIO_DYNAMIC = "",
            .SDL_AUDIO_DRIVER_SNDIO = false,
            .SDL_AUDIO_DRIVER_SNDIO_DYNAMIC = "",
            .SDL_AUDIO_DRIVER_WASAPI = false,
            .SDL_AUDIO_DRIVER_VITA = false,
            .SDL_AUDIO_DRIVER_PSP = false,
            .SDL_AUDIO_DRIVER_PS2 = false,
            .SDL_AUDIO_DRIVER_N3DS = false,
            .SDL_AUDIO_DRIVER_NGAGE = false,
            .SDL_AUDIO_DRIVER_QNX = false,
            .SDL_AUDIO_DRIVER_PRIVATE = true,
            .SDL_INPUT_LINUXEV = false,
            .SDL_INPUT_LINUXKD = false,
            .SDL_INPUT_FBSDKBIO = false,
            .SDL_INPUT_WSCONS = false,
            .SDL_HAVE_MACHINE_JOYSTICK_H = false,
            .SDL_JOYSTICK_ANDROID = false,
            .SDL_JOYSTICK_DINPUT = false,
            .SDL_JOYSTICK_DUMMY = true,
            .SDL_JOYSTICK_EMSCRIPTEN = false,
            .SDL_JOYSTICK_GAMEINPUT = false,
            .SDL_JOYSTICK_HAIKU = false,
            .SDL_JOYSTICK_HIDAPI = false,
            .SDL_JOYSTICK_IOKIT = false,
            .SDL_JOYSTICK_LINUX = false,
            .SDL_JOYSTICK_MFI = false,
            .SDL_JOYSTICK_N3DS = false,
            .SDL_JOYSTICK_PS2 = false,
            .SDL_JOYSTICK_PSP = false,
            .SDL_JOYSTICK_RAWINPUT = false,
            .SDL_JOYSTICK_USBHID = false,
            .SDL_JOYSTICK_VIRTUAL = false,
            .SDL_JOYSTICK_VITA = false,
            .SDL_JOYSTICK_WGI = false,
            .SDL_JOYSTICK_XINPUT = false,
            .SDL_JOYSTICK_PRIVATE = false,
            .SDL_HAPTIC_DUMMY = true,
            .SDL_HAPTIC_LINUX = false,
            .SDL_HAPTIC_IOKIT = false,
            .SDL_HAPTIC_DINPUT = false,
            .SDL_HAPTIC_ANDROID = false,
            .SDL_HAPTIC_PRIVATE = false,
            .SDL_LIBUSB_DYNAMIC = "",
            .SDL_UDEV_DYNAMIC = "",
            .SDL_PROCESS_DUMMY = true,
            .SDL_PROCESS_POSIX = false,
            .SDL_PROCESS_WINDOWS = false,
            .SDL_PROCESS_PRIVATE = false,
            .SDL_SENSOR_ANDROID = false,
            .SDL_SENSOR_COREMOTION = false,
            .SDL_SENSOR_WINDOWS = false,
            .SDL_SENSOR_DUMMY = true,
            .SDL_SENSOR_VITA = false,
            .SDL_SENSOR_N3DS = false,
            .SDL_SENSOR_EMSCRIPTEN = false,
            .SDL_SENSOR_PRIVATE = false,
            .SDL_LOADSO_DLOPEN = false,
            .SDL_LOADSO_DUMMY = true,
            .SDL_LOADSO_WINDOWS = false,
            .SDL_LOADSO_PRIVATE = false,
            .SDL_THREAD_GENERIC_COND_SUFFIX = false,
            .SDL_THREAD_GENERIC_RWLOCK_SUFFIX = false,
            .SDL_THREAD_PTHREAD = true,
            .SDL_THREAD_PTHREAD_RECURSIVE_MUTEX = true,
            .SDL_THREAD_PTHREAD_RECURSIVE_MUTEX_NP = false,
            .SDL_THREAD_WINDOWS = false,
            .SDL_THREAD_VITA = false,
            .SDL_THREAD_PSP = false,
            .SDL_THREAD_PS2 = false,
            .SDL_THREAD_N3DS = false,
            .SDL_THREAD_PRIVATE = false,
            .SDL_TIME_UNIX = true,
            .SDL_TIME_WINDOWS = false,
            .SDL_TIME_VITA = false,
            .SDL_TIME_PSP = false,
            .SDL_TIME_PS2 = false,
            .SDL_TIME_N3DS = false,
            .SDL_TIME_NGAGE = false,
            .SDL_TIME_PRIVATE = false,
            .SDL_TIMER_HAIKU = false,
            .SDL_TIMER_UNIX = true,
            .SDL_TIMER_WINDOWS = false,
            .SDL_TIMER_VITA = false,
            .SDL_TIMER_PSP = false,
            .SDL_TIMER_PS2 = false,
            .SDL_TIMER_N3DS = false,
            .SDL_TIMER_PRIVATE = false,
            .SDL_VIDEO_DRIVER_ANDROID = false,
            .SDL_VIDEO_DRIVER_COCOA = false,
            .SDL_VIDEO_DRIVER_DUMMY = true,
            .SDL_VIDEO_DRIVER_EMSCRIPTEN = false,
            .SDL_VIDEO_DRIVER_HAIKU = false,
            .SDL_VIDEO_DRIVER_KMSDRM = false,
            .SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC = "",
            .SDL_VIDEO_DRIVER_KMSDRM_DYNAMIC_GBM = "",
            .SDL_VIDEO_DRIVER_N3DS = false,
            .SDL_VIDEO_DRIVER_NGAGE = false,
            .SDL_VIDEO_DRIVER_OFFSCREEN = false,
            .SDL_VIDEO_DRIVER_PS2 = false,
            .SDL_VIDEO_DRIVER_PSP = false,
            .SDL_VIDEO_DRIVER_RISCOS = false,
            .SDL_VIDEO_DRIVER_ROCKCHIP = false,
            .SDL_VIDEO_DRIVER_RPI = false,
            .SDL_VIDEO_DRIVER_UIKIT = false,
            .SDL_VIDEO_DRIVER_VITA = false,
            .SDL_VIDEO_DRIVER_VIVANTE = false,
            .SDL_VIDEO_DRIVER_VIVANTE_VDK = false,
            .SDL_VIDEO_DRIVER_OPENVR = false,
            .SDL_VIDEO_DRIVER_WAYLAND = false,
            .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC = "",
            .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_CURSOR = "",
            .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_EGL = "",
            .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_LIBDECOR = "",
            .SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_XKBCOMMON = "",
            .SDL_VIDEO_DRIVER_WINDOWS = false,
            .SDL_VIDEO_DRIVER_X11 = false,
            .SDL_VIDEO_DRIVER_X11_DYNAMIC = "",
            .SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR = "",
            .SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT = "",
            .SDL_VIDEO_DRIVER_X11_DYNAMIC_XFIXES = "",
            .SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2 = "",
            .SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR = "",
            .SDL_VIDEO_DRIVER_X11_DYNAMIC_XSS = "",
            .SDL_VIDEO_DRIVER_X11_DYNAMIC_XTEST = "",
            .SDL_VIDEO_DRIVER_X11_HAS_XKBLIB = false,
            .SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS = false,
            .SDL_VIDEO_DRIVER_X11_XCURSOR = false,
            .SDL_VIDEO_DRIVER_X11_XDBE = false,
            .SDL_VIDEO_DRIVER_X11_XFIXES = false,
            .SDL_VIDEO_DRIVER_X11_XINPUT2 = false,
            .SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_MULTITOUCH = false,
            .SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_SCROLLINFO = false,
            .SDL_VIDEO_DRIVER_X11_XINPUT2_SUPPORTS_GESTURE = false,
            .SDL_VIDEO_DRIVER_X11_XRANDR = false,
            .SDL_VIDEO_DRIVER_X11_XSCRNSAVER = false,
            .SDL_VIDEO_DRIVER_X11_XSHAPE = false,
            .SDL_VIDEO_DRIVER_X11_XSYNC = false,
            .SDL_VIDEO_DRIVER_X11_XTEST = false,
            .SDL_VIDEO_DRIVER_QNX = false,
            .SDL_VIDEO_DRIVER_PRIVATE = true,
            .SDL_VIDEO_RENDER_D3D = false,
            .SDL_VIDEO_RENDER_D3D11 = false,
            .SDL_VIDEO_RENDER_D3D12 = false,
            .SDL_VIDEO_RENDER_GPU = true,
            .SDL_VIDEO_RENDER_METAL = false,
            .SDL_VIDEO_RENDER_VULKAN = true,
            .SDL_VIDEO_RENDER_OGL = false,
            .SDL_VIDEO_RENDER_OGL_ES2 = true,
            .SDL_VIDEO_RENDER_NGAGE = false,
            .SDL_VIDEO_RENDER_PS2 = false,
            .SDL_VIDEO_RENDER_PSP = false,
            .SDL_VIDEO_RENDER_VITA_GXM = false,
            .SDL_VIDEO_RENDER_PRIVATE = false,
            .SDL_VIDEO_OPENGL = false,
            .SDL_VIDEO_OPENGL_ES = true,
            .SDL_VIDEO_OPENGL_ES2 = true,
            .SDL_VIDEO_OPENGL_CGL = false,
            .SDL_VIDEO_OPENGL_GLX = false,
            .SDL_VIDEO_OPENGL_WGL = false,
            .SDL_VIDEO_OPENGL_EGL = false,
            .SDL_VIDEO_STATIC_ANGLE = false,
            .SDL_VIDEO_VULKAN = true,
            .SDL_VIDEO_METAL = false,
            .SDL_GPU_D3D11 = false,
            .SDL_GPU_D3D12 = false,
            .SDL_GPU_VULKAN = true,
            .SDL_GPU_METAL = false,
            .SDL_GPU_PRIVATE = false,
            .SDL_POWER_ANDROID = false,
            .SDL_POWER_LINUX = false,
            .SDL_POWER_WINDOWS = false,
            .SDL_POWER_MACOSX = false,
            .SDL_POWER_UIKIT = false,
            .SDL_POWER_HAIKU = false,
            .SDL_POWER_EMSCRIPTEN = false,
            .SDL_POWER_HARDWIRED = false,
            .SDL_POWER_VITA = false,
            .SDL_POWER_PSP = false,
            .SDL_POWER_N3DS = false,
            .SDL_POWER_PRIVATE = false,
            .SDL_FILESYSTEM_ANDROID = false,
            .SDL_FILESYSTEM_HAIKU = false,
            .SDL_FILESYSTEM_COCOA = false,
            .SDL_FILESYSTEM_DUMMY = false,
            .SDL_FILESYSTEM_RISCOS = false,
            .SDL_FILESYSTEM_UNIX = true,
            .SDL_FILESYSTEM_WINDOWS = false,
            .SDL_FILESYSTEM_EMSCRIPTEN = false,
            .SDL_FILESYSTEM_VITA = false,
            .SDL_FILESYSTEM_PSP = false,
            .SDL_FILESYSTEM_PS2 = false,
            .SDL_FILESYSTEM_N3DS = false,
            .SDL_FILESYSTEM_PRIVATE = false,
            .SDL_STORAGE_STEAM = false,
            .SDL_STORAGE_PRIVATE = false,
            .SDL_FSOPS_POSIX = true,
            .SDL_FSOPS_WINDOWS = false,
            .SDL_FSOPS_DUMMY = false,
            .SDL_FSOPS_PRIVATE = false,
            .SDL_CAMERA_DRIVER_DUMMY = true,
            .SDL_CAMERA_DRIVER_V4L2 = false,
            .SDL_CAMERA_DRIVER_COREMEDIA = false,
            .SDL_CAMERA_DRIVER_ANDROID = false,
            .SDL_CAMERA_DRIVER_EMSCRIPTEN = false,
            .SDL_CAMERA_DRIVER_MEDIAFOUNDATION = false,
            .SDL_CAMERA_DRIVER_PIPEWIRE = false,
            .SDL_CAMERA_DRIVER_PIPEWIRE_DYNAMIC = "",
            .SDL_CAMERA_DRIVER_VITA = false,
            .SDL_CAMERA_DRIVER_PRIVATE = false,
            .SDL_DIALOG_DUMMY = true,
            .SDL_TRAY_DUMMY = true,
            .SDL_ALTIVEC_BLITTERS = false,
            .DYNAPI_NEEDS_DLOPEN = true,
            .SDL_USE_IME = false,
            .SDL_DISABLE_WINDOWS_IME = true,
            .SDL_GDK_TEXTINPUT = false,
            .SDL_IPHONE_KEYBOARD = false,
            .SDL_IPHONE_LAUNCHSCREEN = false,
            .SDL_VIDEO_VITA_PIB = false,
            .SDL_VIDEO_VITA_PVR = false,
            .SDL_VIDEO_VITA_PVR_OGL = false,
            .SDL_XKBCOMMON_VERSION_MAJOR = null,
            .SDL_XKBCOMMON_VERSION_MINOR = null,
            .SDL_XKBCOMMON_VERSION_PATCH = null,
            .SDL_LIBDECOR_VERSION_MAJOR = null,
            .SDL_LIBDECOR_VERSION_MINOR = null,
            .SDL_LIBDECOR_VERSION_PATCH = null,
            .SDL_DISABLE_SSE = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse)),
            .SDL_DISABLE_SSE2 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse2)),
            .SDL_DISABLE_SSE3 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse3)),
            .SDL_DISABLE_SSE4_1 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse4_1)),
            .SDL_DISABLE_SSE4_2 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .sse4_2)),
            .SDL_DISABLE_AVX = !(x86 and std.Target.x86.featureSetHas(cpu.features, .avx)),
            .SDL_DISABLE_AVX2 = !(x86 and std.Target.x86.featureSetHas(cpu.features, .avx2)),
            .SDL_DISABLE_AVX512F = !(x86 and std.Target.x86.featureSetHas(cpu.features, .avx512f)),
            .SDL_DISABLE_MMX = !(x86 and std.Target.x86.featureSetHas(cpu.features, .mmx)),
            .SDL_DISABLE_LSX = !(loongarch and std.Target.loongarch.featureSetHas(cpu.features, .lsx)),
            .SDL_DISABLE_LASX = !(loongarch and std.Target.loongarch.featureSetHas(cpu.features, .lasx)),
            .SDL_DISABLE_NEON = !(arm and std.Target.arm.featureSetHas(cpu.features, .neon) or aarch64 and std.Target.aarch64.featureSetHas(cpu.features, .neon)),
        });
    };

    const headers = b.addTranslateC(.{
        .root_source_file = b.addWriteFiles().add("SDL3.h",
            \\#define UINT64_C(x) (uint64_t)(x)
            \\float SDL_fabsf_REAL(float);
            \\#include "SDL3/SDL_stdinc.h"
            \\#include "video/SDL_sysvideo.h"
            \\#include "audio/SDL_sysaudio.h"
            \\#include "events/SDL_windowevents_c.h"
            \\#include "events/SDL_events_c.h"
            \\#include "events/SDL_keyboard_c.h"
            \\#include "events/SDL_mouse_c.h"
            \\#include "main/SDL_main_callbacks.h"
        ),
        .target = sorvi.resolveSorviTarget(b, target.query),
        .optimize = optimize,
        .link_libc = false,
    });
    headers.addSystemIncludePath(sysroot.headers);
    headers.addIncludePath(sdl3_dep.path("include"));
    headers.addIncludePath(sdl3_dep.path("src"));
    headers.addIncludePath(b.path("include"));
    headers.addConfigHeader(build_config_h);

    const opts = b.addOptions();
    opts.addOption(bool, "sdl2_compat", sdl2_compat);

    const libSDL3 = b.addLibrary(.{
        .name = "SDL3",
        .linkage = .static,
        .version = .{ .major = 3, .minor = 4, .patch = 0 },
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/sorvi.zig"),
            .target = sorvi.resolveSorviTarget(b, target.query),
            .optimize = optimize,
            .link_libc = true,
            .imports = &.{
                .{ .name = "sorvi", .module = sorvi_api },
                .{ .name = "c", .module = headers.createModule() },
                .{ .name = "build_options", .module = opts.createModule() },
            },
        }),
    });
    libSDL3.root_module.addIncludePath(sdl3_dep.path("include"));
    libSDL3.root_module.addIncludePath(sdl3_dep.path("src"));
    libSDL3.root_module.addIncludePath(b.path("include"));
    libSDL3.root_module.addConfigHeader(build_config_h);
    libSDL3.installHeadersDirectory(sdl3_dep.path("include"), "", .{});
    libSDL3.installHeadersDirectory(b.path("include"), "", .{});

    const revision_h = b.addConfigHeader(.{
        .style = .{ .cmake = sdl3_dep.path("include/build_config/SDL_revision.h.cmake") },
        .include_path = "SDL3/SDL_revision.h",
    }, .{
        .SDL_VENDOR_INFO = "sorvi-SDL3",
        .SDL_REVISION = b.fmt("{f}", .{libSDL3.version.?}),
    });
    libSDL3.root_module.addConfigHeader(revision_h);

    var defines: std.ArrayList([]const u8) = .empty;
    defines.appendSlice(b.allocator, &.{
        "-fvisibility=hidden",
        "-DDECLSPEC=",
        "-DSDL_STATIC_LIB=1",
        "-DUSING_GENERATED_CONFIG_H=1",
        b.fmt("-DSDL_BUILD_MAJOR_VERSION={}", .{libSDL3.version.?.major}),
        b.fmt("-DSDL_BUILD_MINOR_VERSION={}", .{libSDL3.version.?.minor}),
        b.fmt("-DSDL_BUILD_MICRO_VERSION={}", .{libSDL3.version.?.patch}),
        b.fmt("-DSDL_SORVI_SDL2_COMPAT_MODE={}", .{@as(u32, if (sdl2_compat) 1 else 0)}),
        "-Wall",
        "-Wundef",
        "-Wfloat-conversion",
        "-fno-strict-aliasing",
        "-Wshadow",
        "-Wno-unused-local-typedefs",
        "-Wimplicit-fallthrough",
    }) catch @panic("OOM");

    libSDL3.root_module.addCSourceFiles(.{
        .flags = std.mem.concat(b.allocator, []const u8, &.{
            defines.items,
            switch (target.result.cpu.arch) {
                .wasm32, .wasm64 => &.{
                    // enables use of more webgl friendly code path
                    "-DSDL_PLATFORM_EMSCRIPTEN",
                },
                else => &.{},
            },
        }) catch @panic("OOM"),
        .files = &.{
            "render/opengles2/SDL_render_gles2.c",
        },
        .root = sdl3_dep.path("src"),
    });

    libSDL3.root_module.addCSourceFiles(.{
        .flags = defines.items,
        .files = &.{
            "SDL.c",
            "SDL_assert.c",
            "SDL_error.c",
            "SDL_guid.c",
            "SDL_hashtable.c",
            "SDL_hints.c",
            "SDL_list.c",
            "SDL_log.c",
            "SDL_properties.c",
            "SDL_utils.c",
            "atomic/SDL_atomic.c",
            "atomic/SDL_spinlock.c",
            "audio/SDL_audio.c",
            "audio/SDL_audiocvt.c",
            "audio/SDL_audiodev.c",
            "audio/SDL_audioqueue.c",
            "audio/SDL_audioresample.c",
            "audio/SDL_audiotypecvt.c",
            "audio/SDL_mixer.c",
            "audio/SDL_wave.c",
            "camera/SDL_camera.c",
            "core/SDL_core_unsupported.c",
            "cpuinfo/SDL_cpuinfo.c",
            "events/SDL_categories.c",
            "events/SDL_clipboardevents.c",
            "events/SDL_displayevents.c",
            "events/SDL_dropevents.c",
            "events/SDL_events.c",
            "events/SDL_eventwatch.c",
            "events/SDL_keyboard.c",
            "events/SDL_keymap.c",
            "events/SDL_keysym_to_keycode.c",
            "events/SDL_keysym_to_scancode.c",
            "events/SDL_mouse.c",
            "events/SDL_pen.c",
            "events/SDL_quit.c",
            "events/SDL_scancode_tables.c",
            "events/SDL_touch.c",
            "events/SDL_windowevents.c",
            "events/imKStoUCS.c",
            "filesystem/SDL_filesystem.c",
            "gpu/SDL_gpu.c",
            "haptic/SDL_haptic.c",
            "hidapi/SDL_hidapi.c",
            "io/SDL_asyncio.c",
            "io/SDL_iostream.c",
            "io/generic/SDL_asyncio_generic.c",
            "joystick/SDL_gamepad.c",
            "joystick/SDL_joystick.c",
            "joystick/SDL_steam_virtual_gamepad.c",
            "joystick/controller_type.c",
            "locale/SDL_locale.c",
            "main/SDL_main_callbacks.c",
            "misc/SDL_libusb.c",
            "misc/SDL_url.c",
            "power/SDL_power.c",
            "render/SDL_render.c",
            "render/SDL_render_unsupported.c",
            "render/SDL_yuv_sw.c",
            "render/gpu/SDL_pipeline_gpu.c",
            "render/gpu/SDL_render_gpu.c",
            "render/gpu/SDL_shaders_gpu.c",
            "render/opengles2/SDL_shaders_gles2.c",
            "render/software/SDL_blendfillrect.c",
            "render/software/SDL_blendline.c",
            "render/software/SDL_blendpoint.c",
            "render/software/SDL_drawline.c",
            "render/software/SDL_drawpoint.c",
            "render/software/SDL_render_sw.c",
            "render/software/SDL_triangle.c",
            "render/vulkan/SDL_render_vulkan.c",
            "render/vulkan/SDL_shaders_vulkan.c",
            "sensor/SDL_sensor.c",
            "stdlib/SDL_crc16.c",
            "stdlib/SDL_crc32.c",
            "stdlib/SDL_getenv.c",
            "stdlib/SDL_iconv.c",
            "stdlib/SDL_malloc.c",
            // These files undef symbol rename if SDL_DYNAPI is not set
            // Reimplemented in src/sorvi.zig
            // "stdlib/SDL_memcpy.c",
            // "stdlib/SDL_memmove.c",
            // "stdlib/SDL_memset.c",
            "stdlib/SDL_mslibc.c",
            "stdlib/SDL_murmur3.c",
            "stdlib/SDL_qsort.c",
            "stdlib/SDL_random.c",
            "stdlib/SDL_stdlib.c",
            "stdlib/SDL_string.c",
            "stdlib/SDL_strtokr.c",
            "storage/SDL_storage.c",
            "thread/SDL_thread.c",
            "time/SDL_time.c",
            "timer/SDL_timer.c",
            "video/SDL_RLEaccel.c",
            "video/SDL_blit.c",
            "video/SDL_blit_0.c",
            "video/SDL_blit_1.c",
            "video/SDL_blit_A.c",
            "video/SDL_blit_N.c",
            "video/SDL_blit_auto.c",
            "video/SDL_blit_copy.c",
            "video/SDL_blit_slow.c",
            "video/SDL_bmp.c",
            "video/SDL_clipboard.c",
            "video/SDL_egl.c",
            "video/SDL_fillrect.c",
            "video/SDL_pixels.c",
            "video/SDL_rect.c",
            "video/SDL_rotate.c",
            "video/SDL_stb.c",
            "video/SDL_stretch.c",
            "video/SDL_surface.c",
            "video/SDL_video.c",
            "video/SDL_video_unsupported.c",
            "video/SDL_vulkan_utils.c",
            "video/SDL_yuv.c",
            "video/yuv2rgb/yuv_rgb_lsx.c",
            "video/yuv2rgb/yuv_rgb_sse.c",
            "video/yuv2rgb/yuv_rgb_std.c",
            "dialog/SDL_dialog.c",
            "dialog/SDL_dialog_utils.c",
            "process/SDL_process.c",
            "tray/SDL_tray_utils.c",

            "camera/dummy/SDL_camera_dummy.c",
            "loadso/dummy/SDL_sysloadso.c",
            "joystick/dummy/SDL_sysjoystick.c",
            "video/dummy/SDL_nullevents.c",
            "video/dummy/SDL_nullframebuffer.c",
            "video/dummy/SDL_nullvideo.c",
            "audio/dummy/SDL_dummyaudio.c",
            "tray/dummy/SDL_tray.c",
            "haptic/dummy/SDL_syshaptic.c",
            "thread/pthread/SDL_systhread.c",
            "thread/pthread/SDL_sysmutex.c",
            "thread/pthread/SDL_syscond.c",
            "thread/pthread/SDL_sysrwlock.c",
            "thread/pthread/SDL_systls.c",
            "thread/pthread/SDL_syssem.c",
            "filesystem/unix/SDL_sysfilesystem.c",
            "filesystem/posix/SDL_sysfsops.c",
            "storage/generic/SDL_genericstorage.c",
            "time/unix/SDL_systime.c",
            "timer/unix/SDL_systimer.c",
            "dialog/dummy/SDL_dummydialog.c",
            "process/dummy/SDL_dummyprocess.c",
            "gpu/vulkan/SDL_gpu_vulkan.c",
            "sensor/dummy/SDL_dummysensor.c",
            "misc/dummy/SDL_sysurl.c",
            "locale/dummy/SDL_syslocale.c",
        },
        .root = sdl3_dep.path("src"),
    });
    b.installArtifact(libSDL3);

    const frontend = sorvi_dep.artifact("sorvi-frontend");

    const Example = struct {
        name: []const u8,
        file: []const u8,
    };

    const examples: []const Example = &.{
        .{
            .name = "clear",
            .file = "examples/01_clear.c",
        },
        .{
            .name = "primitives",
            .file = "examples/02_primitives.c",
        },
        .{
            .name = "lines",
            .file = "examples/03_lines.c",
        },
    };

    for (examples) |example| {
        const core = sorvi.addSorviCore(b, .{
            .name = example.name,
            .root_module = b.createModule(.{
                .target = target,
                .optimize = optimize,
                .link_libc = true,
            }),
        });
        core.root_module.linkLibrary(libSDL3);
        core.root_module.addCSourceFile(.{
            .file = b.path(example.file),
        });
        core.fixup(b);
        const step = b.step(b.fmt("example:{s}", .{example.name}), b.fmt("run {s} example", .{example.name}));
        step.dependOn(&sorvi.addRunSorviCore(b, frontend, core).step);
    }
}
